apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: s5i1u393h-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/s5i1u393h-dotnet-basic-gitops